language: "node_js"
node_js:
  - "node"
install: 
  - npm install
services:
  - mongodb
  - mongoose

scripts:
 - npm run test
 
after_scripts:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
