language: "node_js"
node_js:
  - "node"
cache: 
  directories: 
    - "node_modules"
install: 
  - npm install
services:
  - mongodb
after_success:
  - npm test
  - npm run coveralls
script:
- npm run coveralls